import React,{useEffect,useState} from 'react'
import {api} from './api'

export const roleLabel=(role:string)=>({standard:'Standard user',warehouse_admin:'Warehouse admin',superadmin:'Superadmin'}[role]||role)
const blankUser={username:'',display_name:'',email:'',password:'',role:'standard'}
type Account={id:number;username:string;display_name:string;email:string;role:string;disabled:boolean}
function RoleOptions(){return <><option value="standard">Standard user</option><option value="warehouse_admin">Warehouse admin</option><option value="superadmin">Superadmin</option></>}
export function UsersPage(){
  const [items,setItems]=useState<Account[]>([]),[form,setForm]=useState(blankUser),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  const load=()=>api<Account[]>('/admin/users').then(setItems)
  useEffect(()=>{load().catch(e=>setError(e.message))},[])
  const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');setMessage('');try{await work();await load();setMessage('User saved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const add=(e:React.FormEvent)=>{e.preventDefault();run(async()=>{await api('/admin/users',{method:'POST',body:JSON.stringify(form)});setForm(blankUser)})}
  const update=(u:Account,change:object)=>run(()=>api(`/admin/users/${u.id}`,{method:'PUT',body:JSON.stringify(change)}))
  return <><header className="page-head"><p className="eyebrow">Superadmin</p><h1>Users & access</h1><p>Email addresses are assigned here and cannot be changed by users.</p></header>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}<div className="split"><form className="panel form" onSubmit={add}><h2>Add user</h2><label>Name<input required minLength={2} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label>Username<input required minLength={3} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Temporary password<input required type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><RoleOptions/></select></label><button className="primary" disabled={busy}>Create user</button></form><section className="panel"><h2>Accounts</h2>{items.map(u=><div className="user-row" key={u.id}><div><strong>{u.display_name}</strong><span>{u.username} · {roleLabel(u.role)}</span><span>{u.email||'Email not assigned'}</span></div><div className="user-actions"><select aria-label={`Role for ${u.username}`} disabled={busy} value={u.role} onChange={e=>update(u,{role:e.target.value})}><RoleOptions/></select><button disabled={busy} onClick={()=>{const email=prompt(`Email address for ${u.display_name}`,u.email);if(email!==null)update(u,{email})}}>Assign email</button><button disabled={busy} onClick={()=>{const password=prompt(`New password for ${u.display_name} (at least 10 characters)`);if(password)update(u,{password})}}>Reset password</button><button disabled={busy} onClick={()=>update(u,{disabled:!u.disabled})}>{u.disabled?'Enable':'Disable'}</button></div></div>)}</section></div></>
}

type Connections={read_configured:boolean;update_configured:boolean;api_key_configured:boolean;sync_enabled:boolean;interval_seconds:number;session_days:number}
export function ConnectionSettingsPanel(){
  const [data,setData]=useState<Connections|null>(null),[read,setRead]=useState(''),[write,setWrite]=useState(''),[key,setKey]=useState(''),[clearKey,setClearKey]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  useEffect(()=>{api<Connections>('/admin/connections').then(setData).catch(e=>setError(e.message))},[])
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!data)return;setBusy(true);setError('');try{setData(await api<Connections>('/admin/connections',{method:'PUT',body:JSON.stringify({read_url:read||undefined,update_url:write||undefined,api_key:clearKey?'':key||undefined,sync_enabled:data.sync_enabled,interval_seconds:data.interval_seconds,session_days:data.session_days})}));setRead('');setWrite('');setKey('');setClearKey(false);setMessage('Connection settings saved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="panel delivery-panel"><h2>Inventory connections</h2><p>Signed URLs and keys are never displayed. Leave blank fields unchanged. Resolve queued changes before pointing the app at another workbook.</p>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}{data&&<form className="form" onSubmit={save}><label>Read HTTP URL<input type="password" autoComplete="off" value={read} onChange={e=>setRead(e.target.value)} placeholder={data.read_configured?'Configured — leave blank to keep':'Not configured'}/></label><label>Update HTTP URL<input type="password" autoComplete="off" value={write} onChange={e=>setWrite(e.target.value)} placeholder={data.update_configured?'Configured — leave blank to keep':'Not configured'}/></label><label>Optional API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={data.api_key_configured?'Configured — leave blank to keep':'Not configured'}/></label><label className="check-line"><input type="checkbox" checked={clearKey} onChange={e=>setClearKey(e.target.checked)}/>Remove the optional API key</label><label>Sync interval (seconds)<input type="number" min={10} max={3600} required value={data.interval_seconds} onChange={e=>setData({...data,interval_seconds:Number(e.target.value)})}/></label><label>Remembered sign-in (days)<input type="number" min={1} max={365} required value={data.session_days} onChange={e=>setData({...data,session_days:Number(e.target.value)})}/></label><p className="muted">Applies to new sign-ins. Existing sessions keep their original expiry.</p><label className="check-line"><input type="checkbox" checked={data.sync_enabled} onChange={e=>setData({...data,sync_enabled:e.target.checked})}/>Enable inventory sync and transaction export</label><p className="muted">Pausing keeps local changes queued and stops subsequent inventory and journal passes. An in-progress pass must finish before these settings can be saved. Email delivery has its own switch below.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Save connections'}</button></form>}</section>
}
