import React,{useEffect,useState} from 'react'
import {api} from './api'

const emptyRequest={item_requested:'',manufacturer:'',manufacturer_model:'',quantity:1,notes:'' ,notify_available:false}
export function RequestsPage({user}:{user:{role:string}}){
  const [list,setList]=useState<any[]>([]),[form,setForm]=useState(emptyRequest),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const load=()=>api<any[]>('/requests').then(setList)
  useEffect(()=>{load().catch(e=>setError(e.message))},[])
  const perform=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');setMessage('');try{await work();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const submit=(e:React.FormEvent)=>{e.preventDefault();perform(async()=>{await api('/requests',{method:'POST',body:JSON.stringify(form)});setForm(emptyRequest);setMessage('Request submitted')})}
  const status=(id:number,value:string)=>perform(()=>api(`/admin/requests/${id}`,{method:'PUT',body:JSON.stringify({status:value})}))
  return <><header className="page-head"><p className="eyebrow">Requests</p><h1>{user.role!=='standard'?'Item requests':'Request an item'}</h1><p>Ask for something you need.</p></header>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}<div className="split"><form className="panel form" onSubmit={submit}><label>What do you need?<input required value={form.item_requested} onChange={e=>setForm({...form,item_requested:e.target.value})}/></label><label>Manufacturer <span>optional</span><input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>Master / part number <span>optional</span><input value={form.manufacturer_model} onChange={e=>setForm({...form,manufacturer_model:e.target.value})}/></label><label>Quantity<input type="number" required min="1" step="1" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label><label>Extra information <span>optional</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="check-line"><input type="checkbox" checked={form.notify_available} onChange={e=>setForm({...form,notify_available:e.target.checked})}/>Email my assigned address when available</label><button className="primary" disabled={busy}>{busy?'Saving…':'Submit request'}</button></form><section><h2>{user.role!=='standard'?'Requests':'My requests'}</h2><div className="request-list">{list.map(r=><article className="request" key={r.id}><div><span className={`status ${r.status}`}>{r.status}</span><h3>{r.item_requested}</h3><p>Qty: {r.quantity}{user.role!=='standard'&&` · ${r.requested_by_name}`}</p>{r.manufacturer&&<p>{r.manufacturer}</p>}{r.manufacturer_model&&<p>{r.manufacturer_model}</p>}{r.notes&&<p>{r.notes}</p>}{!!r.notify_available&&<small>Availability email requested</small>}</div>{user.role!=='standard'&&<div className="request-actions"><button disabled={busy||['ordered','complete','closed'].includes(r.status)} onClick={()=>status(r.id,'ordered')}>Mark ordered</button><button disabled={busy||['complete','closed'].includes(r.status)||(r.status==='available'&&!!r.inventory_item_id)} onClick={()=>status(r.id,'available')} title="Add the requested quantity to inventory and notify the requester">Mark available</button></div>}</article>)}{!list.length&&<p className="muted">No requests yet.</p>}</div></section></div></>
}

type RecipientUser={id:number;username:string;display_name:string;email:string;role:'superadmin'|'warehouse_admin'}
type Delivery={admin_emails:string[];recipient_users:RecipientUser[];selected_user_ids:number[];email_enabled:boolean;email_flow_configured:boolean;transaction_export_enabled:boolean;journal_error?:string;last_journal_export?:string;unexported_transactions:number;email_counts:Record<string,number>;recent_emails:{id:number;subject:string;state:string;error?:string}[]}
export function DeliverySettingsPanel(){
  const [data,setData]=useState<Delivery|null>(null),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  const load=()=>api<Delivery>('/admin/delivery-settings').then(setData)
  useEffect(()=>{load().catch(e=>setError(e.message))},[])
  const toggleRecipient=(id:number)=>{if(!data)return;const selected=data.selected_user_ids.includes(id)?data.selected_user_ids.filter(value=>value!==id):[...data.selected_user_ids,id];setData({...data,selected_user_ids:selected})}
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!data)return;setBusy(true);setError('');try{await api('/admin/delivery-settings',{method:'PUT',body:JSON.stringify({recipient_user_ids:data.selected_user_ids,email_enabled:data.email_enabled,email_flow_url:url||undefined,transaction_export_enabled:data.transaction_export_enabled})});setUrl('');await load();setMessage('Delivery settings saved')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const retry=async(id:number)=>{if(!confirm('Check the flow run history first. Retrying an uncertain delivery may send a duplicate email. Continue?'))return;setBusy(true);try{await api(`/admin/notifications/${id}/retry`,{method:'POST'});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="panel delivery-panel"><h2>Email & journal maintenance</h2>{error&&<p className="error">{error}</p>}{message&&<p className="success">{message}</p>}{data&&<><form className="form" onSubmit={save}><fieldset className="recipient-picker"><legend>Request notification recipients</legend><p>Select any active Superadmin or Warehouse Admin account with an assigned email.</p>{data.recipient_users.map(user=><label className="recipient-option" key={user.id}><input type="checkbox" checked={data.selected_user_ids.includes(user.id)} onChange={()=>toggleRecipient(user.id)}/><span><strong>{user.display_name}</strong><small>{user.role==='superadmin'?'Superadmin':'Warehouse Admin'} · {user.email}</small></span></label>)}{!data.recipient_users.length&&<p className="error">No eligible administrators have an assigned email. Add one from Users.</p>}</fieldset><label>Notification flow URL<input type="password" autoComplete="off" value={url} onChange={e=>setUrl(e.target.value)} placeholder={data.email_flow_configured?'Configured — leave blank to keep':'Paste the HTTP trigger URL'}/></label><label className="check-line"><input type="checkbox" checked={data.email_enabled} onChange={e=>setData({...data,email_enabled:e.target.checked})}/>Enable email delivery</label><p className="muted">Your existing email flow is retained. New requests are sent to the selected administrator accounts. Availability alerts go to the requesting user’s assigned email.</p><label className="check-line"><input type="checkbox" checked={data.transaction_export_enabled} onChange={e=>setData({...data,transaction_export_enabled:e.target.checked})}/>Export transactions to the Excel Transactions sheet</label><p className="muted">First replace and save the Inventory Operations Office Script with the supplied updated version. The journal includes time, user, item, quantity and outcome. {data.unexported_transactions} record(s) awaiting export.</p>{data.journal_error&&<p className="error">{data.journal_error}</p>}{data.last_journal_export&&<p>Last journal export: {new Date(data.last_journal_export).toLocaleString()}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save delivery settings'}</button></form><details><summary>Email delivery history</summary><button className="secondary" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh history</button>{data.recent_emails.map(job=><div className="delivery-job" key={job.id}><strong>{job.subject}</strong><span>{job.state}</span>{job.error&&<p>{job.error}</p>}{job.state==='uncertain'&&<button disabled={busy} onClick={()=>retry(job.id)}>Retry after checking flow</button>}</div>)}</details></>}</section>
}

export function DatabaseExport(){
  const [busy,setBusy]=useState(false),[error,setError]=useState('')
  const download=async()=>{setBusy(true);setError('');try{const response=await fetch('/api/admin/database/export',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error('Backup could not be downloaded. Check your session and try again.');const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`inventory-backup-${new Date().toISOString().replaceAll(':','-')}.sqlite`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="panel backup-panel"><h2>Database backup</h2><p>Download a complete local database, including inventory, transactions, users, requests and queued changes. This works even when Excel is unavailable.</p><p className="muted">Keep the file private: it contains account data, email addresses and integration settings. Store your server’s .env configuration and image folder separately for a full recovery.</p>{error&&<p className="error">{error}</p>}<button className="secondary" disabled={busy} onClick={download}>{busy?'Preparing backup…':'Export database'}</button></section>
}
